import "./styles/globals.css";
import "./styles/styles.css";
import "bootstrap/dist/css/bootstrap.min.css";

// META DATA
import type { Metadata } from "next";

// LAYOUTS
import Navigation from "@/navpage";
import Footer from "@/footerpage";

// LIBRARIES
import client from "@/lib/apollo/client";
import { GetAllPages } from "@/lib/graphql/query";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getAllPages() {
  const pages = await client.query({
    query: GetAllPages,
  });

  await client.cache.reset();

  return pages.data.pages.nodes;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = await getAllPages();

  return (
    <html lang="en">
      <body>
        <Navigation data={data} />
        <main className="main-contents">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
